#!/usr/bin/env bash
#This script prints numbers from 1 to 100
#but prints fizz for multiple of 3 and Buzz for multiple of 5 and FizzBuzz for multiple of both 3 and 5
number=1
while ((number <= 100))
do
	if ((number % 3 == 0 && number % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((number % 3 == 0))
	then
		echo "Fizz"
	elif ((number % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$number"
	fi
	(( number++))
done
