#!/usr/bin/env bash
# A shell script that prints from 1 to 12
n=1
while (( n <= 20 ))
do
	echo "$n"
	case $n in
		"4")echo "bad luck from China";;
		"9")echo "bad luck from Japan";;
		"17")echo "bad luck from Italy";;
	esac
	(( n++ ))
done
